In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
a = [1,2,3,4,5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [7]:
l1 = [[1,2,3,],[1,2,3],[1,2,4]]
arr1 = np.array(l1)
arr1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 4]])

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr = np.zeros(7)
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr = np.zeros((4,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr = np.linspace(1,5,10) #gives equal linear Space
arr 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
arr = np.random.rand(10)
arr

array([0.61716465, 0.15060071, 0.98345075, 0.72933786, 0.5505905 ,
       0.29599676, 0.77598309, 0.83346068, 0.01214039, 0.75288936])

In [14]:
np.random.randn(10) #Standardizations

array([ 0.03438932, -0.126562  ,  1.2570574 , -0.6381653 , -0.30885168,
       -0.26651492,  1.09061359,  1.37226345,  0.8567344 , -0.3847936 ])

In [15]:
np.random.randint(6)

5

In [16]:
np.random.randint(10,20,4)

array([19, 15, 18, 18], dtype=int32)

In [17]:
arr = np.array([[1,2,3],[1,2,4],[4,6,7]])
arr

array([[1, 2, 3],
       [1, 2, 4],
       [4, 6, 7]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

In [21]:
arr

array([[1, 2, 3],
       [1, 2, 4],
       [4, 6, 7]])

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(7)

In [24]:
arr.sum()

np.int64(30)

In [25]:
arr

array([[1, 2, 3],
       [1, 2, 4],
       [4, 6, 7]])

In [26]:
np.sum(arr,axis=0) # Column

array([ 6, 10, 14])

In [27]:
np.sum(arr,axis=1) #Row

array([ 6,  7, 17])

In [28]:
arr.mean()

np.float64(3.3333333333333335)

In [29]:
arr.std()

np.float64(2.0)

In [30]:
arr.argmin()

np.int64(0)

In [31]:
arr.argmax()

np.int64(8)

In [32]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Array Indexing

In [34]:
arr = np.arange(0,39)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38])

In [35]:
arr[8]

np.int64(8)

In [36]:
arr[4:8]

array([4, 5, 6, 7])

In [37]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [38]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [39]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38])

In [40]:
arr[0:8:2]# three parameter steps

array([0, 2, 4, 6])

Slicing Matrix

In [54]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [55]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [56]:
arr[1,1]

np.int64(7)

In [57]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [58]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [59]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [60]:
bool_index = arr % 2 == 0
bool_index

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [61]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

Array operations

In [62]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])


In [64]:
arr1 + arr2  # same no of elements (size)

array([ 7,  9, 11, 13, 15])

In [66]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

BroadCasting

In [84]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [85]:
arr + 10

array([20, 30, 40, 50])

Deep and Shallow copy

In [86]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [87]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [88]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [89]:
b = a
b[0] = 10
a

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [90]:
c = a.copy()
c[0] = 14
a

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [100]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(1,5).reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [101]:
arr2

array([[1, 2],
       [3, 4]])

In [102]:
arr1 @ arr2

array([[ 7, 10],
       [15, 22]])

In [103]:
np.dot(arr1,arr2)

array([[ 7, 10],
       [15, 22]])

In [104]:
arr1.T

array([[1, 3],
       [2, 4]])

Advance Manipulation

In [105]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [106]:
np.hstack((arr1,arr2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [109]:
np.column_stack((arr1,arr2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

Splitting 

In [112]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [115]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Exercises

In [135]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [136]:
rows = np.sum(s,axis = 1)

In [137]:
cols = np.sum(s,axis = 0)

In [146]:
x = rows == cols
flag = True
for i in x:
    if i == False:
        flag = False
        break
if flag == False:
    flag
else:
    for i in range(0,9,3):
      for j in range(0,9,3):
        if np.sum(s[i:i+3,j:j+3]) != 45:
            print(False)
            break
    print(True)

        

True


In [200]:
## Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [201]:
data.shape

(5, 3)

In [202]:
data[:,0].mean()  # Average age

np.float64(18.4)

In [203]:
data[:,1] # print Math Marks

array([85, 92, 76, 65, 90])

In [204]:
data[:,2].max() # Highest Science Marks

np.int64(95)

In [206]:
data[:,1]+5

array([90, 97, 81, 70, 95])

In [207]:
data[data[:,2]>90]

array([[17, 76, 95]])

In [209]:
len(data[data[:,0] <19]) #Younger than 19

3

In [210]:
np.mean(data[:,1:],axis = 0)

array([81.6, 83.2])

In [212]:
data[(data[:,1]>=80) & (data[:,2] >= 80)] 

array([[19, 92, 88],
       [20, 90, 85]])

In [217]:
## Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
data[:,2][data[:,2]<75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])